### ISSUE TITLE
Provide/document mechanism to disable SSL verification

### ISSUE THREAD

**Issue by cmdicely** [awslabs/amazon-ecs-local-container-endpoints#15]
Attempting to run the ecs-local-endpoints container on a system behind a corporate proxy that does SSL interception wtih self-signed certificates results in a sequence of errors of the form (excluding timestamp):

> `level=error msg="HTTP 500 - RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: x509: certificate signed by unknown authority"`

Other AWS tools (e.g., the AWS CLI and Python SDK) provide mechanisms to disable certificate verification, but no such mechanism appears to be included for the ecs-local-countainers-endpoints.

**Comment by clareliguori** [comment]
Hi @cmdicely, since one of the main responsibilities for this tool is to pull IAM credentials from your account, I'm not sure I'm comfortable providing an option to disable certificate verification entirely.  That would leave users open to man-in-the-middle attacks and malicious credentials from a fake IAM endpoint.

Does your corporate proxy actually use self-signed certificates, or is there a custom root CA internally that it's using to sign the certs?  Would providing an option to import a custom trust chain into the local-container-endpoints container work for you, so that certificate validation would pass?

**Comment by cmdicely** [comment]
It is actually a custom root CA as you guessed, and, yes, providing the ability to import a custom trust chain should work (and, I agree, is probably a much better idea than disabling SSL cert verification.)

**Comment by clareliguori** [comment]
You should be able to mount in your custom cert bundle into the container at any of the following locations, and it will be picked up by the container's AWS clients:
```
/etc/ssl/certs/ca-certificates.crt
/etc/pki/tls/certs/ca-bundle.crt
/etc/ssl/ca-bundle.pem
/etc/pki/tls/cacert.pem
/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
```

Can you confirm that it works for you?
