### ISSUE TITLE
V4 endpoint support

### ISSUE THREAD

**Issue by alkalinecoffee** [awslabs/amazon-ecs-local-container-endpoints#38]
👋 Hey all, thanks for making this image available.

Is there any planned support for V4 metadata endpoints?  Do we have an ETA on this?

Thanks

**Comment by bvtujo** [comment]
Hi Joe, we don't currently have an ETA but will discuss this and update the issue when we have more information. For the time being, @PettitWesley may know more about the status.

**Comment by PettitWesley** [comment]
@alkalinecoffee @bvtujo I haven't thought about V4 much; I don't have an ETA either. 

In ECS, V4 is the same as V3 except network IO stats are present for all network modes. Previously with V3 they were not present for the awsvpc network mode. AFAICT, the structure used is the same as the one provided by docker stats. Since local endpoints does not have a true awsvpc- network stats should already be present in all stats responses.

So on that front, its not clear to me that any changes are actually needed for this tool- I think you might be able to just set the `ECS_CONTAINER_METADATA_URI_V4` to the same value we recommend for v3 and it would work.

So may be all we need is doc change? Someone should investigate this. I created this project and still try to maintain it, but its no longer my primary focus, I'd prefer if someone else could help out.

**Comment by alkalinecoffee** [comment]
Thanks for the response.  According to the docs, there are a few additional values added to the V4 task endpoint:

```
AttachmentIndex
IPV4SubnetCIDRBlock
MACAddress
PrivateDNSName
SubnetGatewayIPV4Address
DomainNameServers (Fargate tasks only)
DomainNameSearchList (Fargate tasks only)
```

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html

I haven't had a chance to look at the code myself, but is it possible today to mock or otherwise inject other values (perhaps from envvars) into the metadata endpoint response?  That might help make this more flexible in the long-term, as the docs above state that more values may be added over time.  Maybe we can put the onus on the developer to add mocked values as needed instead of having to keep this image up to date with each value.

**Comment by PettitWesley** [comment]
@alkalinecoffee Ah I see. Then we do need to make changes to support V4, to mock those new fields. Right now we have default mocks for metadata fields, which can be overridden with Env Vars, we can take the same approach.

Are you interested in contributing this?

**Comment by PettitWesley** [comment]
Metadata is handled here primarily: https://github.com/awslabs/amazon-ecs-local-container-endpoints/blob/master/local-container-endpoints/metadata/metadata.go

Defaults/env vars here: https://github.com/awslabs/amazon-ecs-local-container-endpoints/blob/master/local-container-endpoints/config/config.go

**Comment by PettitWesley** [comment]
Implementation steps for the full solution:
- #40 adds generic metadata injection from a JSON file
- Add docs for the above feature
- Add an example JSON metadata file for the new fields in V4
- Add docs on V4, tell users to use the same HTTP path as V3

**Comment by iamhopaul123** [comment]
Closing this issue since implementation and docs are now available.
